spring:
  rabbitmq:
    # === connection ===
    host: localhost
    port: 5672
    username: guest
    password: guest


    publisher-confirm-type: correlated # confirms one-by-one;
    publisher-returns: true